### ISSUE TITLE
Incomplete text in the software renderer

### ISSUE THREAD

**Issue by vanfanel** [cyxx/rawgl#1]
Hi, cyxx

First things first, I am VERY happy you continued with the RAW development! :)
Text is partially missing on the software renderer: it's notable because it's missing the greeting from the computer, the information about the experiment on the holographic monitor, and also the password screens.
On some parts, first and last letter of each phrase are visible, but nothing more.

**Comment by cyxx** [comment]
fixed with commit d440a82 !
