### ISSUE TITLE
Pillar boxes wrong color

### ISSUE THREAD

**Issue by BenWlson** [cyxx/rawgl#13]
The pillar boxes on the left/right side of the screen in fullscreen mode with aspect ratio correction on are not consistently black.  When I compiled this from vanfanel's initial fork, the pillar boxes worked correctly, but now that the new commits have been merged, the pillar boxes are filled with a different color from within the game.

**Comment by cyxx** [comment]
not sure if you used software or opengl rendering.
both should be fixed with d58deb957.
