### ISSUE TITLE
Unable to compile f8f666a3 and newer

### ISSUE THREAD

**Issue by monreal** [cyxx/rawgl#15]
I can not compile f8f666a32 on Fedora 24 however I can compile the revision before that (145a518ec97).

$ make
g++ -g -O -MMD -Wall `sdl2-config --cflags` -DBYPASS_PROTECTION   -c -o aifcplayer.o aifcplayer.cpp
g++ -g -O -MMD -Wall `sdl2-config --cflags` -DBYPASS_PROTECTION   -c -o bitmap.o bitmap.cpp
g++ -g -O -MMD -Wall `sdl2-config --cflags` -DBYPASS_PROTECTION   -c -o file.o file.cpp
g++ -g -O -MMD -Wall `sdl2-config --cflags` -DBYPASS_PROTECTION   -c -o engine.o engine.cpp
g++ -g -O -MMD -Wall `sdl2-config --cflags` -DBYPASS_PROTECTION   -c -o graphics_gl.o graphics_gl.cpp
g++ -g -O -MMD -Wall `sdl2-config --cflags` -DBYPASS_PROTECTION   -c -o graphics_soft.o graphics_soft.cpp
g++ -g -O -MMD -Wall `sdl2-config --cflags` -DBYPASS_PROTECTION   -c -o script.o script.cpp
g++ -g -O -MMD -Wall `sdl2-config --cflags` -DBYPASS_PROTECTION   -c -o mixer.o mixer.cpp
g++ -g -O -MMD -Wall `sdl2-config --cflags` -DBYPASS_PROTECTION   -c -o pak.o pak.cpp
g++ -g -O -MMD -Wall `sdl2-config --cflags` -DBYPASS_PROTECTION   -c -o resource.o resource.cpp
g++ -g -O -MMD -Wall `sdl2-config --cflags` -DBYPASS_PROTECTION   -c -o resource_nth.o resource_nth.cpp
g++ -g -O -MMD -Wall `sdl2-config --cflags` -DBYPASS_PROTECTION   -c -o resource_win31.o resource_win31.cpp
g++ -g -O -MMD -Wall `sdl2-config --cflags` -DBYPASS_PROTECTION   -c -o resource_3do.o resource_3do.cpp
g++ -g -O -MMD -Wall `sdl2-config --cflags` -DBYPASS_PROTECTION   -c -o systemstub_sdl.o systemstub_sdl.cpp
systemstub_sdl.cpp:16:40: error: ‘constexpr’ needed for in-class initialization of static data member ‘const float SystemStub_SDL::kAspectRatio’ of non-integral type [-fpermissive]
  static const float kAspectRatio = 4 / 3.;
                                        ^~
<builtin>: recipe for target 'systemstub_sdl.o' failed
make: *** [systemstub_sdl.o] Error 1

**Comment by cyxx** [comment]
should be fixed with 127818ed
