### ISSUE TITLE
Required data files missing from README.md

### ISSUE THREAD

**Issue by monreal** [cyxx/rawgl#16]
The README does not list all required data files, for example it says "Amiga and PC DOS releases (Bank*)" while for the DOS release you also need memlist.bin.

For the 15th anniversary release it says "15th anniversary edition (Pak01.pak)" but complains about missing Intro2004.wav and End2004.wav at least.

I do not have access to the Windows 3.1 release but reading through the code I think it also needs x.mid and y.mid.

Please add the missing information to the README.md

**Comment by cyxx** [comment]
Thanks for the notice.
README has been updated with 8904b96b6b2ac
