### ISSUE TITLE
Wrong sounds with SDL 2.0.5 on Raspberry Pi

### ISSUE THREAD

**Issue by vanfanel** [cyxx/rawgl#17]
Hi,

With current stable SDL and current git versions, some rawgl sound effects are wrong: for example, they keypad on the lab entrance in the intro sequence, the thunder later on...

**Comment by cyxx** [comment]
Which data files are you using ?

**Comment by vanfanel** [comment]
It happens with both PC and Amiga datafiles. That's the ones I am using.

**Comment by cyxx** [comment]
I compared the Amiga data files with both SDL 2.0.4 and 2.0.5, no hearable difference for me under Linux.
Can you detail what is wrong exactly ? Wrong pitch, noise ? Is the music affected or only the sounds ?

**Comment by vanfanel** [comment]
@cyxx: Yes, I can detail it as much as I can:
-Music is NOT affected, only the sound effects.
-Sound effects affected are the "security keypad" keys that Lester presses during the intro sequence, and the thunder effect.
-I would say it's wrong pitch and noise.

**Comment by cyxx** [comment]
I tried valgrind and there are no warning/errors indicating memory corruption.
If it is saturated, can you try if reducing the volume for sounds help at all (to get a clue) ?
The keypad sounds seems to be played as max volume (63) - 
`
diff --git a/mixer.cpp b/mixer.cpp
index ceebd74..ad1157b 100644
--- a/mixer.cpp
+++ b/mixer.cpp
@@ -139,7 +139,7 @@ struct Mixer_impl {
                _sounds[channel] = 0;
        }
        void setChannelVolume(uint8_t channel, uint8_t volume) {
-               Mix_Volume(channel, volume * MIX_MAX_VOLUME / 63);
+               Mix_Volume(channel, MIX_MAX_VOLUME / 2);
        }
`

**Comment by vanfanel** [comment]
@cyxx :
 I have tried the mentioned changes to the mixer code, but there were no differences: some audio effects are still heavily distorted with SDL 2.0.5.

However, the problem does not seem to be with rawgl itself: I have built rawgl on my X86 laptop (I have always used rawgl on the Pi) and the issue is not present there. It's only noticeable on the Raspberry Pi (Raspbian), so unless you have a Raspberry Pi, I think we will not be able to diagnose what's going on.

**Comment by cyxx** [comment]
I also had a try on WIndows via mingw, sounds are playing fine.
I don't have a Pi myself, any idea on the SDL2 (audio) changes between 2.0.4 and 2.0.5 on that platform ?

**Comment by vanfanel** [comment]
@cyxx: I have found the changes from 2.0.4 to 2.0.5, sorry it took me so long to answer here, I have been on exams lately:

https://forums.libsdl.org/viewtopic.php?t=12160

First post there. There have been many audio changes, but I understand they are mostly internal... what do you think?

**Comment by vanfanel** [comment]
@cyxx : I had time to dig into this issue, and I found something strange.
On the Amiga and PC editions, the function to play a sound effect is Mixer_impl::playSoundRaw().
This function uses convertMono8ToWav() to resample from the original sample frequency (freq=10559 in the case of distorted sounds like the keypad sounds and the thunder effect when Lester is teleported underwater with his desk) to a 11025Hz WAV for SDL_Mixer to play.
Well: I analyzed the very first keypad effect after conversion, and the result of the conversion differs between X86_64 and ARM (Raspberry Pi). I am including both results so you can vimdiff them or use the comparision method you want. I am including the first "len" bytes, the complete resampled sample is bigger.
[res_x86_64.txt](https://github.com/cyxx/rawgl/files/1372158/res_x86_64.txt)
[res_rpi.txt](https://github.com/cyxx/rawgl/files/1372159/res_rpi.txt)

So I guess it's a resampling problem on ARM.. or maybe there's something I am obviating here?

**Comment by vanfanel** [comment]
@cyxx : I have been investigating this futher, and I have found something really wrong here.
The DOS and AMIGA versions of AW both use the Mixer_impl::playSoundWav() method to play audio after it has been resampled, etc. Ok, what Mixer_impl::playSoundWav() receives is the same on both X86_64 and ARM (Raspberry Pi): the "data" pointer has the same information on both.
But inside Mixer_impl::playSoundWav(), "data" is loaded onto an SDL_RWops structure with:
`SDL_RWops *rw = SDL_RWFromConstMem(data, size);`
And then rw is used to make up a Mix_chunk structure in:
`Mix_Chunk *chunk = Mix_LoadWAV_RW(rw, 1);`
Well, here's the problem: chunk->abuf pointer does not contain the same data on X86_64 and ARM.
I am attaching the contents of chunk->abuf for the SAME sample (the first keypad press on the intro).
It both cases, it was retrieved with the gdb command:
`x/17608xb chunk->abuf`
exactly after `Mix_Chunk *chunk = Mix_LoadWAV_RW(rw, 1);` has been called and executed.
[chunk_x86.txt](https://github.com/cyxx/rawgl/files/1378977/chunk_x86.txt)
[chunk_rpi.txt](https://github.com/cyxx/rawgl/files/1378978/chunk_rpi.txt)

**Comment by cyxx** [comment]
That's interesting. I agree with your analysis, that seems to indicate the problem is in the SDL_RWFromConstMem() implementation itself. Maybe one way to check further is to check the differences between SDL 2.0.4 and 2.0.5 and if that function code was changed.

**Comment by vanfanel** [comment]
@cyxx would it be possible to build the chunk from "data" and "size" without using SDL_RWFromConstMem() in the middle? As a proof that the problem is there...
I have asked about this on the SDL2 forum:
https://discourse.libsdl.org/t/how-to-access-the-data-pointer-on-an-sdl-rwops-structure/23221

**Comment by cyxx** [comment]
One possibility is be to create a file with the contents of "data", then use SDL_RWFromFile(file, "rb") to pass it to Mix_LoadWAV_RW()

**Comment by cyxx** [comment]
Some pseudo-code would be -

```
FILE *fp = fopen("temp.wav", "wb");
if (fp) {
  fwrite(data, 1, size, fp);
  fclose(fp);
  SDL_RWops *rw = SDL_RWFromFile("temp.wav", "rb");
  ...
}
```

Does that help ?

**Comment by vanfanel** [comment]
@cyxx : yes, thanks :) I did the experiment myself days ago, but in the end I reported to the SDL2 bugzilla as it's an ARM-only issue on SDL2. It's currently being investigated by Icculus himself so we will see a fixed SDL2 version soon, I hope :smile: 

https://bugzilla.libsdl.org/show_bug.cgi?id=3876

**Comment by cyxx** [comment]
Ok, if using SDL_RWFromFile does not fix the issue, that would mean the problem is in Mix_LoadWAV_RW.

**Comment by vanfanel** [comment]
It's now fixed: it's Mix_LoadWAV_RW but indirectly, it was the SDL2 cvt subroutines in the end.
Look at the end of https://bugzilla.libsdl.org/show_bug.cgi?id=3876
RAWGL sounds perfectly again on ARM with that patch, I hope it makes it in time for SDL2 2.0.7 which is due to be released soon.
