### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by eblanca** [cyxx/rawgl#19]
My Another World 20th anniversary edition seems lacking some files.
First, before the game begins (water scene) a warning appears:
`WARNING: Failed to load music '../../giochi/Another World 20th Anniversary Edition/game/OGG/amb5000.ogg', Couldn't open '../../giochi/Another World 20th Anniversary Edition/game/OGG/amb5000.ogg'!`

After a while into the game (I took the gun already) a further warning:
`WARNING: Unable to open '../../giochi/Another World 20th Anniversary Edition/game/WGZ/file163B.wgz'!`
perhaps this is fixable, because I have three of those file163: they are file163-EX-1.wgz, file163-GR-1.wgz and file163-IN-1.wgz . May a simple rename solve this?

**Comment by cyxx** [comment]
Hi,

You are not missing any files, the interpreter simply does not handle these cases. To give more details (eg. what needs to be changed in the code)
- playMusic(5000) is equivalent to stopMusic()
- -EX/-IN/-GR sounds variants are played based on the current ambient music
- -1/-2/-3 suffixes seems to be a random range

**Comment by eblanca** [comment]
Every warning is now gone, great!
Thank you
