### ISSUE TITLE
Demo version is not playable.

### ISSUE THREAD

**Issue by carlo-bramini** [cyxx/rawgl#22]
I downloaded the demo version for MSDOS and I tried it.
The game starts to play the intro, but it is missing some screens and some text messages.
When the intro is finished, it shows the logo of the game but the graphics is corrupted, identically on both GL and software renderers, see attached screenshot.
Finally, when the demo should start the playable part of the game, the engine hangs.

These are the messages printed on the console:

```
Using software graphics
Using DOS data files
WARNING: Unknown string id 0x1f4!
WARNING: Unknown string id 0x1f5!
WARNING: Unknown string id 0x1f5!
WARNING: Unknown string id 0x1f6!
WARNING: Unknown string id 0x1f6!
WARNING: Unknown string id 0x1f7!
WARNING: Unknown string id 0x1f8!
WARNING: Unknown string id 0x1f9!
ERROR: Resource::readBank() unable to open 'bank0c'!
```
I cloned the latest sources of the repository at the time of writing and I compiled RAWGL myself.

![demo](https://user-images.githubusercontent.com/30959007/35195766-89975646-fec8-11e7-9dcf-07b8bd94ac15.png)

**Comment by carlo-bramini** [comment]
I did a checkout of new sources and some issues are resolved.
Interplay screen is now shown.
Missing text messages are also shown.
Logo of the game is also shown with correct graphics.
However, when it reaches the logo screen, the playable part does not start.
Instead it happens that the engine loops forever with 100% of CPU usage in the task manager.
I have seen that it loops inside Resource::load() of resource.cpp
I tried to replace the "continue" statement in this line:

https://github.com/cyxx/rawgl/blob/bb09513d6dbd893a9cdae68ba8e13b3e53a2a80a/resource.cpp#L273

with a "break" instruction, and after that the game started.

**Comment by cyxx** [comment]
Thanks for reporting.
Using "break" is fine if the resource is the last one to be loaded. Otherwise we can change the resource status to STATUS_NULL.

**Comment by carlo-bramini** [comment]
Tested with after a6aeb45: the playable demo now starts.
Thank you.

**Comment by cyxx** [comment]
The issue with the logos not being displayed correctly is related to the palette not being set or set after the polygons are drawn.

This is what the fixUp_palette conditions try to workaround. Some similar code could be added for the screen transitions of the demo version.

**Comment by carlo-bramini** [comment]
With efa2b7f, the demo version is playable, so this issue seems to be resolved for me.

**Comment by cyxx** [comment]
Thanks for testing.
