### ISSUE TITLE
Missing wind blowing sound on intro and first part of the game

### ISSUE THREAD

**Issue by vanfanel** [cyxx/rawgl#3]
On both the original Amiga and PC versions, the wind can be heard blowing in the intro scene before Dr Lester arrives with the car.
The same wind can be heard during the intro in the external views of the lab, when the menacing storm is shown.
Also, the wind can be heard in the first screen, after Lester emerges from the pool and it sounds until he's captured.

The wind blowing sound could be considered a small detatil, but it REALLY adds a lot to the game's ambiance. It gives the sensation of coldness and loneliness on the barren world where Lester's adventures take place.

**Comment by cyxx** [comment]
should be fixed with commit 03ce0374
