### ISSUE TITLE
ALT-X does not exit the game

### ISSUE THREAD

**Issue by vanfanel** [cyxx/rawgl#5]
If the game runs on SDL2 on an X11-based backend, the game can be exited with ALT+F4, but on systems without X11 (like the Raspberry Pi, where the game works GREAT, btw) the game cannot be quit because ALT-F4 doesn't work.

The ALT-X combination does not exit the game in any system, X11 or not.

**Comment by cyxx** [comment]
This looks like a SDL2 and/or WM thing.
https://wiki.libsdl.org/SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4

No problem in adding another key combo to exit, though.

**Comment by vanfanel** [comment]
I have added the ALT-x detection. It couldn't work before simply because this key combination, ALT-x, was not being processed.

**Comment by cyxx** [comment]
fixed with commit 921d2480
