### ISSUE TITLE
Missing aspect ratio correction 

### ISSUE THREAD

**Issue by vanfanel** [cyxx/rawgl#6]
Th engine currently relies on setting a physical video mode for aspect ratio correction, but on most non-X11 systems, SDL_CreateWindow() will not set a physical resolution, so 640x480 is usually scaled to non-4:3 resolutions.
In other words, SDL2 works on systems where it's always "fullscreen", and as things are now, in these systems aspect ratio is lost.

**Comment by cyxx** [comment]
you can use the --window command line option to set the dimensions, although it would be nice to have the AR calculated based on the supported resolutions.

**Comment by vanfanel** [comment]
I have added an option for true fullscreen support: changing the video mode is not a good idea anymore in modern systems, so AR is corrected independently from the physical video mode in use.
This is how it's done in other games/ports.

**Comment by cyxx** [comment]
Thanks, should be in commit f8f666a325. I added changes for the opengl graphics code.
