### ISSUE TITLE
Wind blowing sound loops too fast

### ISSUE THREAD

**Issue by vanfanel** [cyxx/rawgl#8]
The wind blowing sound loops too fast. 
When using the anniversary edition (2004 version, as was sold on GOG) it's very evident, as the wind blowing sound is starting over and over.

**Comment by cyxx** [comment]
to clarify a bit - is that the 15th or 20th edition ?
I am aware looping is not properly handled with the original data files from 1991 releases, but I haven't look at the anniversary editions.

**Comment by vanfanel** [comment]
@cyxx: I have the GOG 15th edition. The wind starts, then cuts, then restarts.

**Comment by cyxx** [comment]
remastered sounds should now be used with the 15th edition, commit 5db86a459
