### ISSUE TITLE
Gas on the tunnel doesn't kill Lester

### ISSUE THREAD

**Issue by vanfanel** [cyxx/rawgl#9]
After Lester and the companion run away from the cage and get into the tower, there's a part where the compation saves Lester from being captured by throwing him to a narrow tunner where Lester has to roll over himself to advance and get to the exit.
There are gas fumes in that tunnel that should kill Lester (as in the original Amiga and PC versions), but they don't.

**Comment by cyxx** [comment]
Which version are you using ?
It seems fine with the DOS and 15th.

**Comment by vanfanel** [comment]
I am using the AMIGA version data.

**Comment by vanfanel** [comment]
@cyxx : I have fired up my Minimig (Amiga 500 FPGA hardware implementation) and noticed the gas fumes don't kill you on the original Amiga version. Sorry again, cyxx. This report has no sense.

**Comment by cyxx** [comment]
It seems the gas killing code is indeed not present in the Amiga scripts.
The DOS code does :

1492: VAR(0xF8) = VAR(0xE6)
1495: VAR(0xF8) += -9
1499: jmpIf(VAR(0x01) < VAR(0xF8) @8389)
149F: VAR(0xF8) += 18
14A3: jmpIf(VAR(0x01) > VAR(0xF8) @8389)
14A9: jmpIf(VAR(0x04) >= 16384, @8389)
14B0: VAR(0x04) |= 16384
14B4: installTask(20, @12EC)

12EC: // START OF SCRIPT TASK
12EC: GFX_0x54
12F1: playSound(res=117, freq=21, vol=64, channel=0)
12F7: playSound(res=122, freq=20, vol=64, channel=3)
12FD: playSound(res=87, freq=20, vol=16, channel=1)
1303: yieldTask // PAUSE SCRIPT TASK
